# Generated by Django 4.0.1 on 2022-04-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_long_url_longtoshort_long_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longtoshort',
            old_name='long_url',
            new_name='Long_url',
        ),
        migrations.RenameField(
            model_name='longtoshort',
            old_name='short_url',
            new_name='Short_url',
        ),
    ]
