# Generated by Django 4.0.1 on 2022-04-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_date_longtoshort_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longtoshort',
            old_name='Date',
            new_name='date',
        ),
    ]
