# Generated by Django 4.0.1 on 2022-04-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_date_longtoshort_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longtoshort',
            old_name='date',
            new_name='Date',
        ),
    ]
