# Generated by Django 4.0.1 on 2022-04-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_date_longtoshort_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longtoshort',
            old_name='clicks',
            new_name='Clicks',
        ),
    ]
